[models]

    [models.LLaMA-2-7B-32K]
    model = "togethercomputer/LLaMA-2-7B-32K"
    temperature = 0.7
    max_tokens = 500
    top_k = 50
    

    [models.RedPajama-INCITE-7B-Chat]
    model = "togethercomputer/RedPajama-INCITE-7B-Chat"
    temperature = 0.1
    max_tokens = 500
    top_k = 50

    
    [models.Pythia-Chat-Base-7B]
    model = "togethercomputer/Pythia-Chat-Base-7B-v0.16"
    temperature = 0.1
    max_tokens = 500
    top_k = 50

    [models.GPT-NeoXT-Chat-Base-20B]
    model = "togethercomputer/GPT-NeoXT-Chat-Base-20B"
    temperature = 0.1
    max_tokens = 500
    top_k = 50


    