[models]

    [models.Llama-2-7b-chat-hf]
    model = "togethercomputer/RedPajama-INCITE-7B-Base"
    temperature = 0.1
    max_tokens = 500
    top_k = 1

    [models.Mistral-7B-Instruct]
    model = "togethercomputer/RedPajama-INCITE-7B-Base"
    temperature = 0.1
    max_tokens = 500
    top_k = 1